# Generated by Django 4.2.29 on 2026-04-17 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CSSD_Management_System', '0002_alter_customuser_options_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('Normal', 'Normal'), ('Urgent', 'Urgent')], default='Normal', max_length=50)),
                ('status', models.CharField(choices=[('Requested', 'Requested'), ('Collected', 'Collected'), ('Cleaned', 'Cleaned'), ('Sterilized', 'Sterilized'), ('Packed', 'Packed'), ('Delivered', 'Delivered')], default='Requested', max_length=50)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('cleaned_at', models.DateTimeField(blank=True, null=True)),
                ('sterilized_at', models.DateTimeField(blank=True, null=True)),
                ('packed_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('current_stock', models.IntegerField(default=0)),
                ('min_threshold', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='RequestItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CSSD_Management_System.inventoryitem')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='CSSD_Management_System.instrumentrequest')),
            ],
        ),
    ]
