# Generated by Django 6.0.3 on 2026-04-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSSD_Management_System', '0004_inventoryitem_alter_customuser_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentrequest',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
