# Generated by Django 6.0.4 on 2026-04-26 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("CSSD_Management_System", "0005_instrumentrequest_is_archived"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="instrumentrequest",
            name="is_archived",
        ),
    ]
