# Generated by Django 6.0.3 on 2026-04-18 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSSD_Management_System', '0005_instrumentrequest_batch_alter_customuser_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentrequest',
            name='last_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
