# Generated by Django 6.0.3 on 2026-04-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSSD_Management_System', '0006_remove_instrumentrequest_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentrequest',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
