# Generated by Django 6.0.4 on 2026-05-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSSD_Management_System', '0007_instrumentrequest_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='sterilizationbatch',
            name='instrument_sets',
            field=models.ManyToManyField(blank=True, related_name='batches', to='CSSD_Management_System.instrumentset'),
        ),
    ]
